//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryRestApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryRestApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Authors
        ///insert into LibraryMGKIT.dbo.Authors (ID,LName,FName,SName,BirthDay,Gender) values (N&apos;DBA53807-9E52-40DE-91F8-5DE9211252F3&apos;,N&apos;Толстой&apos;,N&apos;Лев&apos;,N&apos;Николаевич&apos;,&apos;1862.09.09 0:00:00&apos;,N&apos;м&apos;)
        ///insert into LibraryMGKIT.dbo.Authors (ID,LName,FName,BirthDay,Gender) values (N&apos;FB904AF2-8BE5-455D-9001-9FFDE4CFCD92&apos;,N&apos;Таненбаум&apos;,N&apos;Эндрю&apos;,&apos;1944.03.16 0:00:00&apos;,N&apos;м&apos;)
        ///insert into LibraryMGKIT.dbo.Authors (ID,LName,FName,BirthDay,Gender) values (N&apos;31B4FF79-C54E-463A-9ADB-04EE38BF9031&apos;,N&apos;Макконнелл&apos;,N&apos;Стив&apos;,&apos;1962.09. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateToUP001 {
            get {
                return ResourceManager.GetString("UpdateToUP001", resourceCulture);
            }
        }
    }
}
